/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exo2 */

#ifndef _Included_Exo2
#define _Included_Exo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exo2
 * Method:    pid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Exo2_pid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
