/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exo3 */

#ifndef _Included_Exo3
#define _Included_Exo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exo3
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Exo3_fork
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
