/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exo4 */

#ifndef _Included_Exo4
#define _Included_Exo4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exo4
 * Method:    pid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Exo4_pid
  (JNIEnv *, jclass);

/*
 * Class:     Exo4
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Exo4_fork
  (JNIEnv *, jclass);

/*
 * Class:     Exo4
 * Method:    waitD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exo4_waitD
  (JNIEnv *, jclass);

/*
 * Class:     Exo4
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exo4_exit
  (JNIEnv *, jclass);

/*
 * Class:     Exo4
 * Method:    sleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Exo4_sleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
